/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'status' : BookingStatus,
  'screenshotFileName' : [] | [string],
  'date' : string,
  'name' : string,
  'time' : string,
  'paymentDetails' : PaymentDetails,
  'specialRequest' : string,
  'phone' : string,
  'guests' : bigint,
}
export type BookingStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'confirmed' : null };
export interface PaymentDetails {
  'paymentMethod' : string,
  'upiDetails' : string,
  'bankDetails' : string,
  'advanceAmount' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllBookings' : ActorMethod<[], undefined>,
  'confirmBooking' : ActorMethod<[bigint], undefined>,
  'deleteBooking' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBookingsByStatus' : ActorMethod<[BookingStatus], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectBooking' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBooking' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      string,
      string,
      [] | [string],
      PaymentDetails,
    ],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];