/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentDetails = IDL.Record({
  'paymentMethod' : IDL.Text,
  'upiDetails' : IDL.Text,
  'bankDetails' : IDL.Text,
  'advanceAmount' : IDL.Nat,
});
export const Booking = IDL.Record({
  'status' : BookingStatus,
  'screenshotFileName' : IDL.Opt(IDL.Text),
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'paymentDetails' : PaymentDetails,
  'specialRequest' : IDL.Text,
  'phone' : IDL.Text,
  'guests' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllBookings' : IDL.Func([], [], []),
  'confirmBooking' : IDL.Func([IDL.Nat], [], []),
  'deleteBooking' : IDL.Func([IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectBooking' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        PaymentDetails,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentDetails = IDL.Record({
    'paymentMethod' : IDL.Text,
    'upiDetails' : IDL.Text,
    'bankDetails' : IDL.Text,
    'advanceAmount' : IDL.Nat,
  });
  const Booking = IDL.Record({
    'status' : BookingStatus,
    'screenshotFileName' : IDL.Opt(IDL.Text),
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'paymentDetails' : PaymentDetails,
    'specialRequest' : IDL.Text,
    'phone' : IDL.Text,
    'guests' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllBookings' : IDL.Func([], [], []),
    'confirmBooking' : IDL.Func([IDL.Nat], [], []),
    'deleteBooking' : IDL.Func([IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectBooking' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          PaymentDetails,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };